#!/usr/bin/env node
// Walks client/src/ and server/ to auto-generate architectureData.js.
//
// Strategy:
//   - Existing nodes are preserved as-is (descriptions, positions).
//   - A file is "covered" if its path appears in any existing node's file field.
//   - Uncovered files get new nodes placed in category-specific zones with
//     collision avoidance so they don't overlap existing or newly-placed nodes.
//   - New import-derived edges are added but marked with a placeholder
//     description so the UI can render them faintly.
//
// Run: node scripts/generateArchitecture.mjs

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, relative, dirname, basename, extname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ── Load existing data ─────────────────────────────────────────────────────────
const dataPath = join(ROOT, 'client/src/data/architectureData.js');
let existingNodes = [], existingEdges = [];
try {
  const mod = await import(pathToFileURL(dataPath).href + `?t=${Date.now()}`);
  existingNodes = mod.nodes ?? [];
  existingEdges = mod.edges ?? [];
  console.log(`[arch] loaded ${existingNodes.length} existing nodes, ${existingEdges.length} edges`);
} catch (err) {
  console.warn('[arch] could not load existing data, starting fresh:', err.message);
}

// A node is "auto" if it was previously generated by this script.
// We detect that either by an explicit flag or by the placeholder descriptions.
function isAutoNode(n) {
  if (n.auto === true) return true;
  const w = n.what ?? '';
  const h = n.how ?? '';
  return w.endsWith('— add a description here.') || h === 'Implementation detail — add here.';
}

const curatedNodes = existingNodes.filter(n => !isAutoNode(n));
const priorAutoByFile = new Map();
for (const n of existingNodes) if (isAutoNode(n)) priorAutoByFile.set(n.file, n);
console.log(`[arch]  ${curatedNodes.length} curated · ${priorAutoByFile.size} prior-auto`);

// Curated edges have hand-written descriptions; auto edges start with [auto].
function isAutoEdge(e) { return typeof e[2] === 'string' && e[2].startsWith('[auto]'); }
const curatedEdges = existingEdges.filter(e => !isAutoEdge(e));

// ── Skip patterns ─────────────────────────────────────────────────────────────
// Files matching these are not tracked (too granular / not architecturally
// significant).
const SKIP_PATH_PATTERNS = [
  /^client\/src\/components\/ui\//,     // shadcn primitives + custom UI wrappers
  /\.test\.(js|jsx|ts|tsx)$/,           // tests
  /\.stories\.(js|jsx|ts|tsx)$/,        // storybook
];

// ── Category rules ────────────────────────────────────────────────────────────
const CATEGORY_RULES = [
  [/^server\/whatsapp\//,  'whatsapp'],
  [/^server\/ai\//,        'ai-layer'],
  [/^server\/mcp\.js$/,    'ai-layer'],
  [/^client\/src\/components\/(.*View|AuthScreen|NavigationSidebar|FarmerPortal|UsersView|ArchitectureView|Icons)\.(jsx|js)$/, 'frontend-views'],
  [/^client\/src\/components\//, 'frontend-core'],
  [/^client\/src\/(App|main|constants|routes)\.(jsx|js)$/, 'frontend-core'],
  [/^client\/src\/api\//, 'api-client'],
  [/^server\/routes\//, 'backend-routes'],
  [/^server\/services\//, 'services'],
  [/^server\/(lib|middleware)\//, 'services'],
  [/^server\/models\//, 'models'],
  [/^server\/(index|app|server)\.(js|ts)$/, 'infrastructure'],
];

function categorise(relPath) {
  for (const skip of SKIP_PATH_PATTERNS) if (skip.test(relPath)) return null;
  for (const [re, cat] of CATEGORY_RULES) if (re.test(relPath)) return cat;
  return null;
}

// ── Layout zones for NEW nodes ────────────────────────────────────────────────
// Each category defines an ordered list of rows [gy, xMin, xMax].
// The next free cell (row-major) within these rows is used for placement.
// If all rows are full, overflow rows are added below the last row.
const NEW_ZONES = {
  'frontend-views':  [[0, 12, 22], [1, 0,  22]],
  'frontend-core':   [[3, 0,  14], [4, 0,  14]],
  'map':             [[0, 14, 20], [3, 11, 14]],
  'api-client':      [[5, 0,  14], [6, 0,  14]],
  'backend-routes':  [[7, 0,  14], [8, 0,  14]],
  'services':        [[9, 0,  14], [10, 0, 14]],
  'models':          [[11, 0, 14], [12, 0, 14]],
  'whatsapp':        [[1, 15, 22], [3, 15, 22], [5, 15, 22]],
  'ai-layer':        [[3, 22, 27], [5, 22, 27], [7, 22, 27]],
  'infrastructure':  [[13, 0, 14], [14, 0, 14]],
};

// ── File walker ────────────────────────────────────────────────────────────────
const SKIP_DIRS  = new Set(['node_modules', '.git', 'dist', 'build', '__tests__', 'coverage']);
const SKIP_FILES = new Set(['vite.config.js', 'tailwind.config.js', 'postcss.config.js', 'seedPages.js']);
const TRACK_EXTS = new Set(['.js', '.jsx', '.ts', '.tsx', '.mjs']);

function walk(dir, results = []) {
  let entries;
  try { entries = readdirSync(dir); } catch { return results; }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, results);
    else if (TRACK_EXTS.has(extname(entry)) && !SKIP_FILES.has(entry)) results.push(full);
  }
  return results;
}

const allFiles = [
  join(ROOT, 'client/src'),
  join(ROOT, 'server'),
].flatMap(d => existsSync(d) ? walk(d) : []);

// ── Coverage: which files are already represented by a CURATED node? ─────────
// Auto-generated nodes don't count as coverage — they'll be re-placed.
function fileFragments(fileField) {
  return fileField
    .split('+')
    .map(part => part.split('(')[0].trim())
    .filter(Boolean);
}

const coveredFragments = new Set();
for (const n of curatedNodes) {
  for (const frag of fileFragments(n.file)) {
    coveredFragments.add(frag);
    coveredFragments.add(basename(frag));
  }
}

// Absolute-path → node-id (for edge building) - built for curated first,
// extended with auto nodes as they're placed.
const fileToId = new Map();
for (const n of curatedNodes) {
  for (const frag of fileFragments(n.file)) {
    const full = join(ROOT, frag).replace(/\\/g, '/');
    if (!fileToId.has(full)) fileToId.set(full, n.id);
  }
}

// ── Collision-avoidance layout ────────────────────────────────────────────────
// Only curated positions are pre-occupied. Auto positions are reassigned.
const occupied = new Set();
for (const n of curatedNodes) occupied.add(`${n.gridX},${n.gridY}`);

function nextPosition(cat) {
  const zones = NEW_ZONES[cat] ?? [[20, 0, 20]];

  // Try each configured row in order
  for (const [gy, xMin, xMax] of zones) {
    for (let gx = xMin; gx <= xMax; gx += 2) {
      if (!occupied.has(`${gx},${gy}`)) {
        occupied.add(`${gx},${gy}`);
        return { gx, gy };
      }
    }
  }

  // Overflow: extend downward from the last configured row
  const [lastY, xMin, xMax] = zones[zones.length - 1];
  for (let dy = 1; dy < 20; dy++) {
    const gy = lastY + dy;
    for (let gx = xMin; gx <= xMax; gx += 2) {
      if (!occupied.has(`${gx},${gy}`)) {
        occupied.add(`${gx},${gy}`);
        return { gx, gy };
      }
    }
  }
  // Should never get here — put it far away
  return { gx: 60, gy: 40 };
}

function makeId(rel) {
  return rel
    .replace(/^client\/src\//, '')
    .replace(/^server\//, '')
    .replace(/\.(jsx?|tsx?|mjs)$/, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .toLowerCase()
    .replace(/^-|-$/g, '');
}

// Marker in a description that lets the UI dim auto-generated edges.
const AUTO_EDGE_MARKER = '[auto]';

// ── Discover new nodes ─────────────────────────────────────────────────────────
const newNodes = [...curatedNodes];
let addedNodes = 0, replacedAutoNodes = 0;

for (const full of allFiles) {
  const rel = relative(ROOT, full).replace(/\\/g, '/');
  const cat = categorise(rel);
  if (!cat) continue;

  const isCovered = coveredFragments.has(rel) ||
    [...coveredFragments].some(frag => frag.endsWith(rel) || rel.endsWith(frag));

  const fullKey = full.replace(/\\/g, '/');

  if (isCovered) {
    if (!fileToId.has(fullKey)) {
      const owner = curatedNodes.find(n =>
        fileFragments(n.file).some(f => rel.endsWith(f) || f.endsWith(rel))
      );
      if (owner) fileToId.set(fullKey, owner.id);
    }
    continue;
  }

  // Preserve descriptions of any prior auto node for this file
  const prior = priorAutoByFile.get(rel);
  const id    = prior?.id ?? makeId(rel);
  if (curatedNodes.some(n => n.id === id)) continue;

  const pos = nextPosition(cat);
  const label = prior?.label ?? basename(rel, extname(rel));

  newNodes.push({
    id,
    label,
    category: cat,
    gridX: pos.gx,
    gridY: pos.gy,
    height: prior?.height ?? 1,
    file: rel,
    auto: true,
    what: prior?.what ?? `${label} — add a description here.`,
    how:  prior?.how  ?? 'Implementation detail — add here.',
  });
  fileToId.set(fullKey, id);
  if (prior) replacedAutoNodes++; else addedNodes++;
}
console.log(`[arch]  +${addedNodes} new auto nodes, ${replacedAutoNodes} auto nodes re-placed`);

// ── Import parser ─────────────────────────────────────────────────────────────
const IMPORT_RE = /(?:import\s+(?:[^'"]*from\s+)?|export\s+[^'"]*from\s+|require\s*\(\s*)['"]([^'"]+)['"]/g;

function parseImports(filePath) {
  let src;
  try { src = readFileSync(filePath, 'utf8'); } catch { return []; }
  const deps = [];
  for (const [, spec] of src.matchAll(IMPORT_RE)) {
    if (!spec.startsWith('.')) continue;
    const resolved = resolve(dirname(filePath), spec);
    for (const ext of ['.js', '.jsx', '.ts', '.tsx', '.mjs', '/index.js', '/index.jsx']) {
      const candidate = resolved.endsWith(ext) ? resolved : resolved + ext;
      if (existsSync(candidate)) { deps.push(candidate); break; }
    }
  }
  return deps;
}

// ── Discover new edges ────────────────────────────────────────────────────────
// Start from curated edges only (drop stale auto edges — they'll be regenerated
// from the current import graph).
const edgeSet = new Set(curatedEdges.map(e => `${e[0]}|${e[1]}`));
const newEdges = [...curatedEdges];
let addedEdges = 0;

for (const full of allFiles) {
  const srcId = fileToId.get(full.replace(/\\/g, '/'));
  if (!srcId) continue;
  for (const depFull of parseImports(full)) {
    const dstId = fileToId.get(depFull.replace(/\\/g, '/'));
    if (!dstId || dstId === srcId) continue;
    const key = `${srcId}|${dstId}`;
    if (edgeSet.has(key)) continue;
    edgeSet.add(key);
    newEdges.push([srcId, dstId, `${AUTO_EDGE_MARKER} ${srcId} imports from ${dstId}.`]);
    addedEdges++;
  }
}

// ── Sort nodes ────────────────────────────────────────────────────────────────
const CAT_ORDER = Object.keys(NEW_ZONES);
newNodes.sort((a, b) => {
  const ai = CAT_ORDER.indexOf(a.category);
  const bi = CAT_ORDER.indexOf(b.category);
  if (ai !== bi) return (ai < 0 ? 99 : ai) - (bi < 0 ? 99 : bi);
  if (a.gridY !== b.gridY) return a.gridY - b.gridY;
  return a.gridX - b.gridX;
});

// ── Serialise ─────────────────────────────────────────────────────────────────
function jsStr(s) {
  return `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function serNode(n) {
  const autoLine = n.auto ? `    auto: true,\n` : '';
  return [
    `  {`,
    `    id: ${jsStr(n.id)}, label: ${jsStr(n.label)}, category: ${jsStr(n.category)},`,
    `    gridX: ${n.gridX}, gridY: ${n.gridY}, height: ${n.height},`,
    `    file: ${jsStr(n.file)},`,
    autoLine +
    `    what: ${jsStr(n.what)},`,
    `    how: ${jsStr(n.how)},`,
    `  }`,
  ].join('\n');
}

const output = [
  `export const nodes = [`,
  newNodes.map(serNode).join(',\n'),
  `];`,
  ``,
  `// Each edge: [sourceId, targetId, description]`,
  `// Descriptions starting with '[auto]' are import-derived and rendered faintly.`,
  `export const edges = [`,
  newEdges.map(e => `  [${jsStr(e[0])}, ${jsStr(e[1])}, ${jsStr(e[2])}]`).join(',\n'),
  `];`,
  ``,
].join('\n');

writeFileSync(dataPath, output, 'utf8');
console.log(`\n[arch] +${addedNodes} nodes, +${addedEdges} edges → ${newNodes.length} total nodes, ${newEdges.length} total edges`);
